# Generated by Django 2.2 on 2021-01-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210114_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
